### ISSUE TITLE
Make Bogus work with RSpec < 2.14

### ISSUE THREAD

**Issue by psyho** [psyho/bogus#27]
We fixed the deprecation warning, but it broke Bogus on old RSpec versions.

```
/home/vagrant/.gem/ruby/1.9.3/gems/bogus-0.1.2/lib/bogus/rspec.rb:8:in `block in <top (required)>': undefined method `backtrace_exclusion_patterns' for #<RSpec::Core::Configuration:0x0000000131d480> (NoMethodError)
```
